task 0

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,13 @@
 #!/bin/bash
 
-python3 "$PYFILE"
+pyfile="$PYFILE"
+
+if [ -z "$pyfile" ]; then
+  echo "Error: PYFILE environment variable is not set."
+  exit 1
+elif [ ! -f "$pyfile" ]; then
+  echo "Error: File '$pyfile' does not exist."
+  exit 1
+fi
+
+python3 "$pyfile"
